# Generated by Django 4.1.7 on 2023-03-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('station_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
