# Generated by Django 4.1.5 on 2023-03-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
