# Generated by Django 4.1.7 on 2023-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(max_length=20)),
                ('from_station', models.CharField(max_length=30)),
                ('to_station', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('seat_type', models.CharField(max_length=10)),
                ('seat_quantity', models.IntegerField()),
            ],
        ),
    ]
