# Generated by Django 4.1.5 on 2023-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutus_descrption_alter_aboutus_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='link_user',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
