# Generated by Django 4.1.7 on 2023-03-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_trips_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
